---
title: "Fieldwork and Field Experiments"
author:
- affiliation: <cdgrady21@gmail.com>,  Senior Metrics Advisor,
    United States Agency for International Development.
  name: Chris Grady
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  beamer_presentation:
    template: ../utils/bowerstemplate.beamer
    toc: yes
  ioslides_presentation: default
  slidy_presentation: default
bibliography: ../utils/cdg_references.bib
---

```{r include=FALSE, cache=FALSE, eval=F}
require(knitr)
opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="tiny",    # slightly smaller font for code
  echo=TRUE,
  results='markup',
  strip.white=TRUE,
  fig.path='figs/fig',
  cache=FALSE,
  highlight=TRUE,
  width.cutoff=132,
  out.width='.9\\textwidth',
  fig.retina=FALSE,
  message=FALSE,
  comment=NA)
```

<!--
I've done about 18 months of fieldwork since August of 2014 in Ghana, Nigeria, and Malawi.

Ghana: first project, first real overseas travel (did go to Italy a few month's before).  

Nigeria: two projects.  
- One evaluating the effects of a Hausa-language TV channel on interethnic/religious tolerance, women's empowerment, youth empowerment.  Around the time Boko Haram was very active, wanted to reduce support for group's like Boko Haram.
- The other about farmer-pastoralist conflict; farmers and semi-nomadic pastoralists (animal herders) fight over land a lot.  More people, less land, these groups come into conflict a lot in the Sahel and especially in Nigeria.  Evaluating the effect of a big NGO peacebuilding program to reduce conflict.

-->

# Roadmap

- Implementation Partners
- Being in the Field
- Intervention and Evaluation
  - Data collection methods
- Running the Show



# What is a field experiment?

- An experiment done outside of a lab, with real people who don't know they are part of an experiment
  - Lab: show people video, survey those people
  - Field: Show a video in a local theatre; survey people who attended
- Researchers assign and administer experimental intervention

\smallskip

- Different than natural/quasi-experiment where intervention is incidentally random or as-if random <!--You don't administer anything or make sure randomization is being done correctly in one of these. -->


# Implementation Partners

How to get involved with implementers

  - Professor throws you a project
  - Meet at a conference
  - Pro bono "cold call" from you
  - University collaborations
  - Sites that connect researchers and implementers: research4impact, egap, others

- Implementers want prior RCT experience, experience in-country
- Bigger NGOs will want established professors

# Implementation Partners

How to work with non-academics

  - Theoretical vs. practical divide <!--Works on paper, not in real life.  Figure out what really matters about the theory and how to put the theory into practice -->
  - Compromise away from perfection
  - Avoid jargon
  - Explain how long data work can take <!--They will have no idea -->
  - Expect Googledocs
    
# Implementation partners

Priorities and incentives

  - Implementing organizations will want you to do a lot of work that is irrelevant for you
  - Look our for your own interests
  - Implementers _need_ to make themselves look good to maintain grant funding

# Being in the Field

- You need to go <!--or you need to pay a really good partner and communicate daily-->
- You want to go <!--You will get to go to wondrous places few people ever see -->
- Establish personal relationships or you will be in the dark and nothing will get done
- Bring gifts that are identifiably _American_

\smallskip

- Implementer priority: show their project is successful, not to evaluate if the project was successful.

\note{

You need to be involved with the intervention, not lead it from afar.

Otherwise you'll find out 6 months later that they did not like the randomization and so didn't use it.  Or that they started the intervention before the baseline survey because they didn't want to wait.  Or that a control site and treatment site are less than 1 mile apart.  Or that they changed the intervention and it's totally different now (NGOs are _always_ adapting).

}

# Being in the Field

<!--These things apply to almost all international travel, so forgive me if these are already extremely obvious to all of you. -->
- Learn the language actively <!--With a little effort, can say every simple thing in local language within 1 month. -->
- Learn and follow cultural etiquette <!--Normally very easy, about being respectful.  But don't compromise yourself; stop if you feel uncomfortable.-->
- Calm yourself when you want to start an argument <!--Story about going to Mustafa's and his wife not eating with us, I thought it was disrespectful towards women but she would have been very uncomfortable eating with us.  Isaac and non-alcoholic wine. -->

# Being in the Field

- Don't bring anything you are afraid to lose
- If not staying in a fancy hotel, be ready for lack of water/electricity

\medskip

- Start slow and increase intake of local food each day
- Learn what you can and cannot get in-country <!--Contact solution, good coffee are rare. -->
- Get a local phone and simcard
- Get personal wifi connection


# Being in the Field

- Learn to get around without help
- Find amenities and activities -- gyms, basketball/soccer club, local bars
- Travel when possible -- do **not** watch TV in a hotel room
- Hang out with locals
- Bring books to read

\medskip

- Enjoy it!  Make friends!

# Interventions and Evaluations

- Don't let the tail wag the dog -- don't change the intervention so that it can be evaluated more easily
- Make implementers part of design discussions so it is a _team_ design, not _your_ design
- Be flexible where things are not imperative
- Be firm where things are necessary <!--"Chris isn't being unreasonable.  I talked to some people and they said it isn't an experiment if you don't have randomization and a control group." -->


# Interventions and Evaluations

- Field experiments are a mess -- multiple things will go wrong
- Randomization at multiple levels
- Simple designs are more likely to be implemented faithfully; complex designs are beautiful and fragile
- Feasibility extends to survey questions and implementation, observational monitoring procedures, everything
  - Survey experiments are hard on enumerators because the question wording changes every interview

\smallskip

- To NGOs, two-arm RCTs are already complicated.  
- Difficult to pitch more complicated things, like multi-arm designs, saturation designs, etc...

# Interventions and Evaluations

- Everything is clustered
- Everything spills over

\bigskip

- Get the Gerber and Green book.


# Data Collection Methods

- Surveys <!--Lots of tablet survey applications, should learn to code yourself -->
    - In person
    - Mobile phone "IVR" surveys
- Observational measures
- Naturalistic behavioral games
- Focus groups and "Key Informant" interviews
- Others?

\note{
- Questions in one context make no sense in another context
- Yes/No + how strongly do you feel > likert scales.
- Huge agreement bias.


Would you be comfortable with someone from the same religion but a different denomination marrying into your family?
Would you be comfortable with someone from a different religion marrying into your family?

Would you accept someone from a different religion seeking your hand in marriage without converting? - 85% no
Would you accept someone from a different religion seeking marriage with one of your family members without converting? - 85% no

Would you marry someone you loved, even if they practiced a different religion? - 50% yes, 50% no.


There is more than one valid interpretation of religious teachings.

An Arabic word Bid'ah means innovation, connotation heretical teachings.  Innovations -- unorthodox interpretations of Koranic teachings -- are often blamed for violence in NE Nigeria.  So lots of tolerant people said no.

A woman should have a say in how her household spends money.  

}


# Running the Show

- You are in charge and there is no reset button or second chance
- Putting your money into it -- sometimes necessary (get per diem)
- Staying up until 3am every night for two weeks
- Hard deadlines

# Running the Show

- Lead by example: get sweaty, get cold, get uncomfortable
- Don't ask others to do what you will not do
- Be SUPER ORGANIZED


# Conclusion

- Fieldwork and field experiments are great opportunities for researchers
- Working with implementation partners can be difficult but rewarding
- Enjoy experiencing another country
- Keep your designs simple
- Use multiple methods of data collection
- Lead by example

# Conclusion

- Do you really want to do a field experiment/RCT?

\medskip

- Take a lot of time
- Require a lot of non-academic work
- High fail rate


